apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAZOnRV8/uMxBG4jglHTBSJldfcoSD7NDHWyj51JjPuztp8jtr8EZwkrLF08YDxAX55yhSvtn1H44N/x0mS2XAMRZhFexUg7dbIW+AmxfKXw1D4zI5Fa7gf+msp9i3Vr6BvsDcz1LBodO95qnCKreUg5oqGwl3xCYEoGEDoOCRs5VdBMPxQYNKEci7L4ItSEk1LZFJkaOeV6el+WprEsRO8pLeCwlkiTua9LRaYMBwyNgZFvHIrnNSpG5r64MoDeNMk2LOF3U+nLUUvzB9A4264kiZbDSONQ4JdCDxdgog8SzRzLSog+giKH+9GkYJDDrFMUe63rAG00TTStu5rNcw3Iz2+FUXNXCCOFpRIZ1o36FSSI4DndfYXc15OtEAs3sRBRrsY0dzvd9EYf8mjMQWzeRFq56QmhpmsF5Poe6y5IM9cA/RxbdoZw3XjKgNrAZUltpQNH87BOk/BMLSmd0hUagx5ogHdQAqpmAhnkQXRb3jRuJur/dH6vhM3w1q1bsdN3YqtzwpD+JggjPrR/3tVXXBlOzt2Vq3yJ5vC4cHGZEgG/CHnjPLPey9/n4JtmLjVy2HbtUhfvlYzoxAy1KMNUA75AXlti5LhP7ltHROniDAVuF90c7sxYiTiiQevyZ0TBPMSMKzAQFOwEn3NMSQTVFKXi2rJtz5EppWkQOt4MiVpSXmy5p07E1Y/KKumwsriUHkWfmKEjIsrwMJR1WqUqfVl4/Py9Ovv8osgiXTZGukabRGeN5tj0jvbOoez5O45FeKXpUQE+6sWQ9iUL5BHPPtCl8eUY0mWlI9YBDTqxsws0xI3vLyvXYnvNer9sYDx/pcoWwJit+uWKsP1ZQaXSQ7AnS7HoTp08VFkkSR+62N5TpitYfYOtC84NMaAhrw/C+DiW6q/8zbk4gDcN8A54xKJhqOL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

