apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBBDHiGVGe2NVDmeTse+KGD4IqXYZ7DUgTgOGNPEmnioC0GIjTtK9Lqc9aiYoGW1/KjeU2zR44v9hOVbxI20mYH8/HaxcvFbN32rmAJUrbdhyikkhh6jELJ33yHtfSa0aaOQCkrzqOH2fpm30semY5J59cAVqddNpwGzjD2xcoJ2XxuEBMeF24dZ4VvOuaRw3n47N9qRPRBhPc9qnuumDPrU1KrBF7YruSWbG5bWiBU3nLUV4QzY9zhoC8EFAuoSLImFZ5VwdPUFtkXpj0hnGiQFQs4fcqoXnnn08VuVwE1g8MFS20PhJGQt6WXQTFMJlvy6oCYU82K08MWzBZ1YpmG1F7aILJyfVqavQvwQHBm21CZZdUrmA9hQ/+x8I0lLLHtuaTlDtXoWnFmIA+Eluxw2WboHH+74OQH0MZRmNDTmfkktxwvz69TlUT2fuMZbcGbhK6u1rhf1nNWsX41/kkCABRueDpTIsu4RgWhGh2F2QbkzlzFvDr4nV+r5GU6FU2FkxiCLDAWMZ1tXhjVnYU7jdiU26m+VVXf1uK02+/g37BrclZZj7LBKJwBrDZEYVz7YlEmEVwLnXBKQ6NIqKl1CmgFJqrSPaPHfeXqSJ5sJObc5Gg+og2D4vVaxQK+heYBFeNt83IfxPUnGijLNAP/IldwT5HmsGcuIMl93JYrqL7aPUvSVo4hV0uxDUerlDWgsdAq5i6FVgnv/3jAB8HAbja8ZzdsV8yzA2nXpWIBIYHf3NvAxoLpQ9qI4AcTIElSKb+B8KKLDy0lHvYxjyGPDWx31B2Wa0rXD/KnYMDtyCnCWZn3p4UIwsNkChlRnjvf3EQNm6jw95YonQqQ0iLliFwT9seA85Jx37aeO3xct52pGG5R/FHp7y2nQ91EI7Z5YaQRE1579rTIkV03yVa4eaJNXwCy
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

