apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        image: alinbalutoiu/argocd:v2.0.3
        # image: cyrilix/argocd:v2.0.1
        command: [argocd-server, --staticassets, /shared/app, --insecure]

