apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      initContainers:
      - name: copyutil
        image: alinbalutoiu/argocd:v2.0.3
        # image: cyrilix/argocd:v2.0.1
