apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        image: alinbalutoiu/argocd:v2.0.3
        env:
          - name: ARGOCD_EXEC_TIMEOUT
            value: "8m"
