apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: ./
    repoURL: https://github.com/cetic/helm-mlflow.git
    targetRevision: master
    helm:
      parameters:
      - name: image.repository
        value: alborotogarcia/arm64v8
      - name: image.tag
        value: arm-mlflow
      - name: backend_store_uri
        value: "postgresql://mlflow:mlflow@postgres.db-system.svc.cluster.local:5432"
  destination:
    namespace: yatai-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
