apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-grid
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: chart/selenium-grid
    repoURL: https://github.com/pedrodotmc/docker-selenium.git
    targetRevision: selenium-grid-helm-chart
    helm:
      parameters:
      - name: isolateComponents
        value: true
      - name: components.router.imageName
        value: seleniarm/router
      - name: components.router.imageTag
        value: 4.0.0-beta-1-20210215
      - name: components.distributor.imageName
        value: seleniarm/distributor
      - name: components.distributor.imageTag
        value: 4.0.0-beta-1-20210215
      - name: components.eventBus.imageName
        value: seleniarm/event-bus
      - name: components.eventBus.imageTag
        value: 4.0.0-beta-1-20210215
      - name: components.sessionMap.imageName
        value: seleniarm/sessions
      - name: components.sessionMap.imageTag
        value: 4.0.0-beta-1-20210215
      - name: components.sessionQueuer.imageName
        value: seleniarm/session-queuer
      - name: components.sessionQueuer.imageTag
        value: 4.0.0-beta-1-20210215
      - name: hub.imageName
        value: seleniarm/hub
      - name: hub.imageTag
        value: 4.0.0-beta-1-20210215
      - name: chromeNode.imageName
        value: seleniarm/node-chrome
      - name: chromeNode.imageTag
        value: 4.0.0-beta-1-20210215
      - name: firefoxNode.imageName
        value: seleniarm/node-firefox
      - name: firefoxNode.imageTag
        value: 4.0.0-beta-1-20210215
      - name: operaNode.enabled
        value: false
        
  destination:
    namespace: selenium-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
