apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDFHqPAjj43TdKbB/6uP9VH1H+IS631Nb0azwVsu7ol1gsclfC8ZI1VbxZK0DngP+xDoicfdkrLCmFitYER375CXw6RkIQHI5e4lcBpFH7/49jabKjEJnaEfqSMiWvwIXuBXvQ5ilTnM/Ogzf5w971PBwmoCLh7J/+XOD01YCOwnYK5lQIwu/na4VBgS7G2p4fDdXMWEAG5eHkMyFsl0a3dq/a/vuyMa4j76tMoRjpDoMQwL96FfRi9kjyI3iRxrLd7TbiFbnIt9Lxm0+MfWGkqyy+6qpvIib/2GQ5YCU8cPgsL1s+BjmjkjodnOlQH0ZT3jBPxwUAg38DTm9alpz2/EkgNlnr7/1hqtu2R1iLQ6aGj3Cc65pUGVkex46hJAz66w8L8sB8koaJhX7ukBDsv8gUKoVfkLUDqcSJX8xdIQdTQuUU3mT7ZbKw5JKg4O7xzlz5eq44qLKKjwbsWUGNZiUcnAWi0n/ecsTuE6YitJIS+7GwLUZGEePpjfCtEZsfi7C3agkQRWXj4rQqEZfl1j/2EiIqttjwKzUesH5FBjHoZdSB9kolMX7LsgR7oGSNVkElse154OovA54XJ3g4zLjhgFVpO+sprj/qFWWhyc/Zziqd652iJ+VOZl6DKmYbV7LzbH2ZsVZ6WgDO1ch30HpnCKTM4hjQiW+jDug0ipewpttdng70J9Ug/TtMlWjdHIoPOSmyO4zohYvlUHdxyI0S2ivivvEEObGSsnV1Uw5IJlmOkcoRF
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

