apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAo7EzbqKYyhkdFNcqH5vhOuCuhCdzTESbHUsLCTdP4Q1UJLBg7HGbqaFbyym3GrZ0yEgsyP7qYXPOgJejgJVPDm8JCbX5UOa48JmAz3nBziIqxdDxFUcpncStZ97v2/Xt437WhQ87mkHsrCM8xWUHsgmHCf4/01U7ZDPp1elqgQ6BP5YWVxiPz12LtFxmsv7sWN2OhzS/b2MDO052cyejEJ4qej3ociAB5T/xS6SY9n0ZiGbN4Oc9iFkgOJ+lq7okfqwK7xO3OIjl/s7GSzKezO9NFLus2G7cWou7NuTBFkkZAVHHOQ7FHzh0rGE7XGocJBjfvFQ9STIEkwC5DVD0QdT1UZMbrJPbSnvxfdGXNwDX1vJKVr2hHSX1MhFtbCkXr8er8GhHRON+g/Xz5qH7bFRYiEos/4t/pll5Wxwb3xbdhUfPjgPIC6hMlepyHiRMeVi/DsUD3yMOYMrMnJRg9HW+nk+zCplIDr0Ac6UxF2lbdQ6KoJdwBGIl24U6/YkiEk5UvBDuT1tOBYNjXW76JYDqfHA0eeM3kGt+ub/iOARXPyowLB/49NlG+vjelWgM373uilstUPJ5DMBLnRDtcp7gq/Nzo6Sl9O6RyARzMEfZvgcDTmZmu5IqoEM9ORiH9K4MHKSX/3+I4/Gq9NJnyfFcfrH4lp/PuHeYbF+wiu7jTCm4hOOHfqYhe3f0j9ACQ5upHjhMOytlarjgiRx7m+FsqzRRts78sIa9PcZjdkGNeR9JZYgfE
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

