apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgC4oU7L4poJ6cdWVVrpvgG9I0qhMpi5N5IhpkBLhn2VgVnaaAtiV4gH0uDPkvK+M4XF9qljZUgZXhyqsys/nPceGjZ1EEzR/HQ6iyJnmnfL46aRVbQ114SGWSZPb8s8rFk8dd60QK+9NXQL6NckUGZRrILWRXRW8LhOgrSkgUpd/61+2ZTaBRELFQm0ZKTFVKacJU1nq/FrXaRJer8Uv1fZDkt4jkOYHoc2t83sYCiYfYSzkjb1F7rlXIp8mTHQI2Whs/wtrSrbOV0N5r/asCaluD8uM+SpHOGWM5EkhN5/Un0bE7ulVTXO3TvgF+6CnhknAhT1NG4oCi8jz4vEL9R8Rt5HkxVCWndW871QAT2BEBQKy+eagsdClI3T73JPRL+nZ3trvGgHYCq1ncHZdqmNyY/bZpHTOVDGOFOmyOUfMkwhqCv3xUzxVSxSIZT/+yx3MPdOT75ZYtceYm5FZY6kd2FmSTd3SRHVWaulRshC94o1hBDBv+KChkKdKWeDgiKs3CmBxJX6/Yd/eqZqmM8vWtKayfBhp87Ogs5yuAU+yKMwOQnSpZKt0Yrh3l2Ur//4YSgICEihO94z1HjclsdSXm923oyHdKCqZjMYtI7M9WhhWCZ378Fi5Roz0AhqlvTWgZT+Moi7PrXUWe0rnUF43SmSdPlxnr4aaIBwp+9m0VE7HYY2zIEce2kkTccEme9FtVDSSLGxIcXTSRCLYsMpGr6Zixbf3IKeTVKvxV+YBTli35qzlIeP
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

