apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA/mT//ocVD077MpGeBX7/RbfoCv2NottyKyWFsnDVV6C9oOyYtp9blqwn6GRMw7eYQ64R+oSkT0nq/2Xgxh+1TnGjpGQEuQky9UEw5q2nW4Kvs02fjiD0K3+O/X4AsLQTLBxDkvdIgyxZIUU9k5VOYQ/vL5AZI0M7qRlyJaHCmvAvzbHHMb/hNXcBaUPkCb/kV9p+ANYi+otdaW4mpk8tbxSi65x8u2b0QmevaHnvr7SKFKc1CvGjWhJJv5Uh52w06RdC0Vcx7/kZk38putrJ8Exia+RVLifRLg+Bs/O06TdVN9k1s0LAqY0pD385GlRc8pOSKAUxexo6BpqmIk6H0vUVED8UUPBFyLu6VNzB8ChDR+Oc6weXbO5FZgCGdJt0v6sf27zARE0MoWfPZBQ3M4YIrdmtLSnCxnQOep9S67pilAAv9vvrzwwPmRBlnwMUDiVAGZEuBJ4P+5/Cf2jfoOSLiiYsEpr3mhcdMrN0JTDAknERZDfbArjTcG1IfLOQyrZ99uy6zn47uJH5XASH29DFhnlCVHoxBCIZo7S5yd4Y0AlI8ZN7BDXCF33X5nfZy8bPPENwhySpWvNHJ5fsuAgPWpSQ5j41UL+7wGw3bRBsQpVyoyfu9sIaYL8JET4r0f7kRWZE7SwWfIWRu2h8ShQNYyzyYS4rznsKPJK94WOZsLsYQHa7uACNCCuhwRytGQkNjKoS+44q5kUQMvII0VzxuzChhwwNNcGis1EcZ9qI7L8ESJkof
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

