apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAybQmjMLeAYuuapXKYUU5NwfoMbKFBdyP0J5pmGjIEhboCtdrShMgn+NNsfr0CVb//VWVBnToSPI62Rjw2AEua20/B1X/GxjB9CxA0uyY4MVtMaCSNfd+uZ9n5SmL4+rYof4qDRxakfOItHrt/9umBLeV+/qOEC8FANmqSL56K61fbVAu3DjG2/IX2U1J9BJa+fy28MviCwIEKH/ngEq6Q9XKSXC6fMVQo4LOVDUAiV5SVbIb5tsPp3WUEd2DHeXIklAhJppcYD18XmzmsZwEyAoS5ZxtFqe1W72FhT7zTsvf3C0ui6CiFH48WbtlIFcCfFN+eUBSbwHCDqAne7D1mvVffYk1va7JL4KcNjN8c7NL4fGiyV2qa9ZoxUqvS41xhoTt53xpIaTr1S6iAqfslXe5Us/mG6fYQ1KUuVqdMvM8K8UTDT2Dozhzstw9E0liRf3i0Wf6sU9aeqMT1HvjQSQ5nRdswgsTJbK2nSM9coyHqDqiSIaQ0c6MwdKHgrpmkPdtNz0zCVGrNBKoDkK8Uwp8k1qHUPW5ULDEAvdXHFy2fUWXcr/MUgRbmtTPN0BEfutoIVs0Vx/O5oGNd3M0eYVLNVJ8ZpcgKAwEZElacwNgd5BHFTULMPukjfSkN80yFeVR5YtoaDDeggwyYTDTvJa6vquANzupZFzpRaEO5sUNbZNzw32yfOO92f6V+IWjxTHwU3d0rR9C7ORQGNPCLb9V3TdK6Injj1bjBl79OQDErTtXm2VOM
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

