apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDOPTg0C3jueYtzVeZnaUA0B51kKEOi2VSA9nT8/88CXjidsJLOvxLhDdJ1tGnulFk9Bz4GKfKikm1jsJzEe3GPFqA5sFtnJh3zxMTfi5Jd7vHJWiixanaAD5xgSjMVKQk64uZWaKeOeBCN/xy4uTkMvevQutJWboCFJds0PTCv0dBgARSco1wkmsfABZRDdt65Q8lJBjRGQrtWc4JaDntEDQClryJhoIVWuHYvLw2J9Qdd6/YAyNQ8syEhrXjjjnIDIHTkF2krhXWNJ6KKmBzryno5+8qQHvEa/HxTPgNo4QkYoOvRhFNS+wtlyVgSiKMfI1qayZL7oFa8oS8vWONMDJn/ShPfc0KjUZRZDgGGTA42y/r1bnKyBMUoEyO8bTnnyYpXL6+FNqSFi0wF+XSZCvNi2xrgR355AS7de/uXsto9vSRbo4Ggy7DKXHqyvg1u3lVMb8y2Wsu1TN6rqKv1J867kdVwkYt3vl1exmyNE17NyTP+mU39K7m4DL+Btk5tFuOVmm3FUuQrrjc1FBOFmkGKtcqa/MwLtCGoRPllI5W/29xoQi+IAIW9zIqgtS3zZH6OlR+w961DQmUC7wlXQtx0+YG5OwkVI1oVescYfCqYOz3yJW28hL2cIR0PyEd9Zx25gu60L4SIuC0ZgkcPOkiIx8P2d3YqoL7OGF01m5pfBbUjNChS4ILfNFbcx0a6UW+XpAHvGlMwFnA6YncvvXQ8RzxMYK3K+6ilxkd/inXA36qGNpHM
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

