apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAbkc8LxS0R2gfDHV9RNdSb5Nnk2SswtO24g+ztxkdmiXQuUlT2ryBpsTSyPIv1wCkW3buRnjZsaQS5Akid0I6cTF9Cjll8I3AdK9QP+x8wjOBABP9CBBrPYiOsbttWzS9n9cyO2PJNS9cNla+W2qm4qkrGzrZO5MEB7UXtE8LpJA46W9MkxRsdva3ovTVT8izm8gs1kXQz904TnJoLDZjkcJ4/+NeCrKH+1IAtN1rQOAseskVNFcZ9P6CTcsH9zZRIjlm2i0srD4YdkR4hgSuagmB8nnOFyi8/F2u01j2Eb68L85WfCtR8w3XIzOaxG//1oi6Aj8PKwA0rsULaT4uUP6IJOcZCoE1D1QYMaGQOVkbgsQTx2aabm81VbLBYwIRmqfdmNDPIYJpYUUPXrBFRKaNldoh6SQ9mXjdojN6s00LvE0PqfYfU5khll7IpqphwIp78TOqDbiMKa7UPKFC/DGzbxA1GkGW7e4piMDgzA/B35JCiVlz0LORIPAF60hyedYHZ80Ng9ljG1JMrR187zDI+PloYFTyqQMIaUFVwnEUgDAlLUwXqfi68/0hvPv2VM5aWRqjLP61iwX8ukKGfOqXLsNMKv2XYzB9PmpBdvA8egrwLDGw7S1lKBB6Gmu7M0ulc6gHtDfyIC9p1CUcX9ERkbMRyhbmO1FC1TvzHE7WIBUX1Ce7cZxbst4PjYj/XUBc1Fd5ByAJlcG6RLmIyVZ/SCf73293npqnECLMqyD4Hg0Oz+S7H
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

