apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCsBjWFmHDuli11t2vh9lSLWWUs4ZEiGMejg3H0i1219G8qsSXbyk21zD2FVKa8E13r2zLlwcZ4fWgvOJsMMQ+LxVjk1+8eGodx1Nc8kDs0lsEPAgNL+7p80/lmPVXIK9Jj1nHc42p37+p9var66yKwGi7MD+28OuUZC6+pQGG/oA/8l+Joo0U5KaRgP+oNbKTF02mBcY2hZuKiwPmggRkANSWzXQRDMbQsqkdj27gaRtHE5s7nQQfJVD6jS6+QgS7N9wS358ZLOy4pz5D10Gt/6a9JqlwMHMq6QPEP9fE/IEawluCH7iKBazTtglxylx3+xZumbHnOUYum0G1pthYus3JlJU20+u8nS0EvDxa/D4FJ1PI8XcCNywIIZG7emqpMoCeRPMB6Up8+XwMsSI6Zt5Pzej1rv41TGt+HHEswAjBTFMZ9Z0Wh7EzTBbH1DLIXx4N9HEY7gQ6gyzVj1o8ePWmDXGv1+xPgfAylS5uHZ/9rTvRhlDfbb4hRimBbqA1EmSfAGWawMk/DRa5YwYVFlxhTOHCqzjiNYYyGz8qmGhQB7a3FArfz/4kNYMkUq2WFv0MnZyqf98QYrhLL1viVLw4fDrqJBbXCwkRFq4gLgmlrq2cazCWAYDu0chx8EmXHucrYjWt58kXoywP7mDH4k4ZYSVv35k4OBfxgtNnM8mN+DtzVzUHNEaJci0xkqT7m94jLLbyTfcKmlPlfyj574HMaDbpgY6ze0Fb+oIFUyKLpW/Q3tjhB
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

