apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA3paj/F+1cwE28wZPC2VC1KgSOvnLaKZlcTyeB9rvC80qoHDtr3gk5MkuVK9ShozkUuvwrkiFg7SY3ZDxYKtwSW3sl+Ee+0RY+ZlLPrb7t1PLqYDRovfdTITtxefu1vnnSVXlUZwihreYAXyQ4mOYQoQTn/QLy1y3Vv7PTtkGfqLA6SWViECGZOy8Bir/Y7adosszsc9FKIckAZFglbPXfXb1E3SWMnURTKm6+53f0c52neKFYS3TUMG1NHQsd9LHLVBxIKtbKFrUHgPLIAI6beSZnFNOK1B4xaGb10JVW3ZcwHixp5CROY3+zT/MBCAZwhBUta2ch97BfJ+ev0654URQ5DEHAtLIiEmBJVS1GqJ9XFTtIvZRTW31TBAlE7T8GVqXIdMfEzMVtAF8GwUVarv0GYwDEilvqG9mv+nl+NkyW/sYAr7oauAVxFyiv2EPtmdMcF1SWRrdFSbEjCDqvnUft3WYXqDzOPqCmA3cHT8qRW1QJJ+EbQbdAmeAesmMH8KCp5xiMnASrdKbQ/se7V2c6e2eFQPYfuSUKZFlbIwv/bwvDQcghZB8IfEYrowk3Y0AQwHkRTt5+o+bA6a06Z6W6ss+BHTvv1Xr+3vCM4ZjY6gEXUS/9uY3iRHejbUck6jiy0cBTTQ2fi8/Ntc2e7/u5/r84pp6Nn/j1DojpGgHJt+QaQZ4xSsWU3I3Q20bszVxpRgPPTGx1b+nJo5P5xG6FH2XPcELQL3ZnOWUaWvbWiFxrsKtV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

