apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- event-sources.yaml
- sensors.yaml
- githubcred.yaml
patchesStrategicMerge:
- eventbus-controller-deployment.yaml
- sensor-controller-deployment.yaml
- eventsource-controller-deployment.yaml
namespace: argo-events
# images:
#   - name: argoproj/sensor-controller
#     newName: alvarogg777/sensor-controller
#     newTag: v1.3.1
#   - name: argoproj/eventbus-controller
#     newName: alvarogg777/eventbus-controller
#     newTag: v1.3.1
#   - name: argoproj/eventsource-controller
#     newName: alvarogg777/eventsource-controller
#     newTag: v1.3.1
# patchesStrategicMerge:
#   - |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: eventsource-controller
#     spec:
#       template:
#         spec:
#           containers:
#             - name: eventsource-controller
#               env:
#                 - name: EVENTSOURCE_IMAGE
#                   value: alvarogg777/eventsource:v1.3.1
#   - |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: sensor-controller
#     spec:
#       template:
#         spec:
#           containers:
#             - name: sensor-controller
#               env:
#                 - name: SENSOR_IMAGE
#                   value: alvarogg777/sensor:v1.3.1
